matrix:
  include:
    - env: ENV=bionic-lxd
      dist: bionic
      arch: ppc64le
    - env: ENV=xenial-lxd
      dist: xenial
      arch: ppc64le
 
script:
# Environment information
- echo "==> Environment information <=="
- uname -a
- cat /etc/os-release
- grep ^processor /proc/cpuinfo
- free -h
- df -h
- cat /etc/resolv.conf
- arch
- lscpu
